// src/components/Search.vue
<script lang="ts">
import { medicines } from "../MedicineList.js";
import { ref, watch } from "vue";

export default {
  setup() {
    const search_query = ref("");

    const add_to_counter = (e) => {
      for (let i = 0; i < medicines.value.length; i++) {
        let medicine = medicines.value[i];
        if (medicine.name == e.target.textContent) {
          medicine.is_countered = true;
          medicine.chosen_quantity = 1;
          medicine.is_searched = false;
          search_query.value = "";
        }
      }
    };

    watch(search_query, () => {
      for (let i = 0; i < medicines.value.length; i++) {
        let medicine = medicines.value[i];
        if (
          medicine.name.includes(search_query.value) &&
          search_query.value.length > 0
        ) {
          if (medicine.stock > 0) {
            medicine.is_searched = true;
          }
        } else {
          medicine.is_searched = false;
        }
      }
    });

    return { medicines, search_query, add_to_counter };
  },
};
</script>

<template>
  <input type="text" v-model="search_query" />
  <div class="medicine-list">
    <div v-for="medicine in medicines">
      <div v-if="medicine.is_searched" @click="add_to_counter">
        {{ medicine.name }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.medicine-list {
  position: absolute;
  width: 13rem;
}
</style>

// src/components/Search.jsx
import { createSignal, For, Show, createEffect } from "solid-js";
import styles from "./Search.module.css";
import { medicines, set_medicines } from "../MedicineList";

function Search() {
  const [search_query, set_search_query] = createSignal("");

  const searching = (e) => {
    set_search_query(e.currentTarget.value);
    for (let i = 0; i < medicines.length; i++) {
      if (
        medicines[i].name.includes(search_query()) &&
        search_query().length > 0
      ) {
        set_medicines(i, { is_searched: true });
      } else {
        set_medicines(i, { is_searched: false });
      }
    }
  };

  createEffect(() => console.log(medicines));

  const add_to_counter = (e) => {
    for (let i = 0; i < medicines.length; i++) {
      if (medicines[i].name == e.target.textContent) {
        set_medicines(i, { is_countered: true });
        set_search_query("");
      }
    }
  };

  return (
    <>
      <form>
        <input type="text" value={search_query()} onInput={searching} />
      </form>
      <div class={styles.medicine_list}>
        <For each={medicines}>
          {(medicine) => (
            <>
              <Show when={medicine.is_searched}>
                <div class={styles.is_countered} onClick={add_to_counter}>
                  {medicine.name}
                </div>
              </Show>
            </>
          )}
        </For>
      </div>
    </>
  );
}

export default Search;
