// src/components/Storage.jsx
import { For } from "solid-js";
import { medicines } from "../MedicineList";
import styles from "./Storage.module.css";

function Storage() {
  return (
    <>
      <div>Storage List</div>
      <div class={styles.storage_list}>
        <div class={styles.storage_item}>name</div>
        <div class={styles.storage_item}>price</div>
        <For each={medicines}>
          {(medicine) => (
            <>
              <div class={styles.storage_item}>{medicine.name}</div>
              <div class={styles.storage_item}>{medicine.price}</div>
            </>
          )}
        </For>
      </div>
    </>
  );
}

export default Storage;

// src/components/Storage.vue
<script>
import { medicines } from "../MedicineList";

export default {
  setup() {
    return { medicines };
  },
};
</script>

<template>
  <div class="storage-list">
    <div class="storage-list-right">name</div>
    <div class="storage-list-right">price</div>
    <div class="storage-list-right">quantity</div>
    <template v-for="medicine in medicines">
      <div class="storage-list-right">{{ medicine.name }}</div>
      <div class="storage-list-right">{{ medicine.price }}</div>
      <div class="storage-list-right">{{ medicine.quantity }}</div>
    </template>
  </div>
</template>

<style scoped>
.storage-list {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  border-left: solid 2px black;
  border-top: solid 2px black;
}

.storage-list-right {
  border-right: solid 2px black;
  border-bottom: solid 2px black;
}
</style>
